version: '3'

services:
  web:
    build: ./web
    ports:
      - ${PAY_APACHE_PORT}:80
    command: sh /init.sh
    volumes:
      - ${PAY_SOURCE}:/var/www/html/source
      - ./web/sites:/etc/apache2/sites-enabled
      - ./web/init.sh:/init.sh
      - ./logs/web:/var/log/apache2

  mysql:
    image: mysql:5.7
    ports:
      - ${MYSQL_HOST_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8888:80

  adminer:
    image: adminer
    ports:
      - 4567:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
volumes:
  mysql:
